#!/bin/sh

# Set personal aliases

#alias tor-browser='tor-browser --dir="$XDG_DATA_HOME/tor-browser"'
alias sxiv='sxiv -a'
alias mutt='mutt -F ~/.config/mutt/muttrc'
alias tshark='COLORTERM=truecolor tshark --color'
alias ip='ip -color'
alias ls='ls --human-readable --literal --color=auto --group-directories-first'
alias ipa='ip a'
alias mkdir='mkdir --parents --verbose'
alias vim='nvim'
alias reboot='systemctl reboot'
alias poweroff='systemctl poweroff'
alias suspend='systemctl suspend'
alias tp='trash-put'
alias yt="youtube-dl --add-metadata --ignore-errors"
alias yta="yt --extract-audio --format bestaudio/best"
# "Reading configuration file" useless clutter
alias ncmpcpp='ncmpcpp -q'

alias z='zathura'

# Privileged access
if (( UID != 0 )); then
    alias svim='sudo -e'
    alias p='sudo pacman'
    alias ctl='sudo systemctl'
fi

# stop bad deleting
alias rm='printf '\''\033[5m%s\n'\'' "You are stupid!!!"'

# Clean up home
#  alias wget='wget --hsts-file=${XDG_CACHE_HOME}/wget/wget-hsts'

