#!/bin/sh

# Set to correct resolution on desktop
xrandr --output DP-2 --mode 2560x1440 --rate 144
# set wallpaper
xwallpaper --zoom ~/wallpaper.jpg &
# Use Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources
# picom for transparency and blur
picom -b --experimental-backend 
# Speed typing rate up    
xset r rate 300 50 & 
# Remove mouse when idle    
xbanish & 
# Fixes xdotool using wrong keyboard layout
setxkbmap -synch  
# Setup japanese ime
fcitx-autostart
# should screw up clipboard for fcitx
xclip -sel p </dev/null
xclip -sel c </dev/null

# Open apps on startup
st&
st&
st&
brave&
#firejail firefox&
