#!/bin/sh

# Enable color in less
export LESS_TERMCAP_mb=$'\E[01;38;5;11m'
export LESS_TERMCAP_md=$'\e[01;38;5;11m' \
export LESS_TERMCAP_me=$'\e[0m' \
export LESS_TERMCAP_se=$'\e[0m' \
export LESS_TERMCAP_so=$'\e[01;38;5;12m' \
export LESS_TERMCAP_ue=$'\e[0m' \
export LESS_TERMCAP_us=$'\e[01;38;5;3m' \

# Set personal aliases, overriding those provided by oh-my-zsh libs,

alias sxiv='sxiv -a'
alias mwallet='monero-wallet-cli --config-file .config/monero-wallet-cli/config.conf'
alias tshark='COLORTERM=truecolor tshark --color'
alias ip='ip -c'
alias ls='ls --color'
alias ipa='ip a'
alias mkdir='mkdir -p -v'
alias vim='nvim'
alias reboot='systemctl reboot'
alias poweroff='systemctl poweroff'
 
## Safety features
alias cp='cp -i'
alias mv='mv -i'
#alias rm='rm -I'

# Privileged access
if (( UID != 0 )); then
    alias svim='sudo -e'
   alias suspend='sudo systemctl suspend'
    alias p='sudo pacman'
    alias ctl='sudo systemctl'
fi

# Save attachments correctly
alias mutt='cd ~/junk && mutt'

# Clean up home
#  alias wget='wget --hsts-file=${XDG_CACHE_HOME}/wget/wget-hsts'

