#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
 [ -x "$f" ] && . "$f"
done
unset f
fi

export _JAVA_AWT_WM_NONREPARENTING=1 # for android studio
/home/./jalio/.config/xprofile
systemctl --no-block --user start xsession.target
exec dwm

