#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --output DP-2 --mode 2560x1440 --rate 144        # Set to correct resolution on desktop
xwallpaper --zoom ~/wallpaper &                         # set wallpaper
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources       # Use Xresources colors/settings on startup
picom -b --experimental-backend                            # picom for transparency and blur
#dunst &			                                        # dunst for notifications
xset r rate 300 50 &                                    # Speed typing rate up    
xbanish &                                               # Remove mouse when idle    
#sxhkd &                                                 # Simple X hotkey daemon
setxkbmap -synch                                        # Fixes xdotool using wrong keyboard layout

# Open apps on startup
st&
st&
st&
firefox&
